[versions]

# Third party libraries
lib-jetbrains-annotations = "24.1.0"
lib-lombok = "1.18.30"

# database libraries
lib-hikari = "4.0.3"
lib-sqlite = "3.45.1.0"
lib-mysql = "8.0.23"
lib-mariadb = "3.3.2"

[libraries]

# Third party libraries
jetbrains = { group = "org.jetbrains", name = "annotations", version.ref = "lib-jetbrains-annotations" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lib-lombok" }

# database libraries
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "lib-hikari" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "lib-sqlite" }
mysql = { group = "mysql", name = "mysql-connector-java", version.ref = "lib-mysql" }
mariadb = { group = "org.mariadb.jdbc", name = "mariadb-java-client", version.ref = "lib-mariadb" }